name: "Master Docs Publication"
on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install Dependencies
        run: |
          uv pip install --system -e ".[dev]"
      
      - name: Build Docs
        uses: ammaraskar/sphinx-action@8.2.3
        with:
          docs-folder: "./docs/"
      
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./docs/build/html/"